<?php
/**
 * Created by PhpStorm.
 * User: quocd_000
 * Date: 05/03/2015
 * Time: 11:36 PM
 */
Qdmvc::loadPage('product_cat_card');
class Qdmvc_Page_Manufactor extends Qdmvc_Page_ProductCat_Card {
    protected static function getViewClass()
    {
        return 'Qdmvc_View_Manufactor';
    }

    public static function getPage()
    {
        return 'manufactor';
    }

    protected static function initFields()
    {
        $obj = parent::initFields(); // TODO: Change the autogenerated stub
        unset($obj['General']['Fields']['parent_id']);
        unset($obj['General']['Fields']['_parent_name']);
        unset($obj['General']['Fields']['level']);
        return $obj;
    }

}