<?php
/**
 * Created by PhpStorm.
 * User: quocd_000
 * Date: 08/02/2015
 * Time: 11:32 PM
 */
//import libraries
Qdmvc::loadLayout('layout_cardnavigate');

class Qdmvc_View_Contact_Card extends Qdmvc_Layout_CardNavigate
{
    protected function serverFunctions()
    {
        $obj = parent::serverFunctions();
        $obj = array_merge($obj, array(
            'btn_view_in_frontend' => array(
                //'fn_name' => 'btn_view_in_frontend',
                'label' => array(
                    'vi-VN' => 'Mở trang Liên hệ',
                    'en-US' => 'Open Front-End About Page'
                )
            ),
        ));
        return $obj;
    }

    protected function onReadyHook()
    {
        parent::onReadyHook(); // TODO: Change the autogenerated stub

        ?>
        <script type="text/javascript">
            (function ($) {
                $(document).ready(function () {
                    $('#lookup_cs_address_district_id').click(function () {
                        var lurl = $(this).data('lookupurl');
                        var province_id = $('#ctl_address_province_id').val();
                        if (province_id != '') {
                            lurl = MYAPP.addDataPortFilter(lurl, 199, 'provinceid', province_id);// '&filterdatafield199=provinceid&filtervalue199='+province_id+'&filtercondition199=EQUAL';
                        }
                        MYAPP.requestLookupWindow(lurl);
                    });

                    $('#lookup_cs_address_ward_id').click(function () {
                        var lurl = $(this).data('lookupurl');
                        var district_id = $('#ctl_address_district_id').val();
                        if (district_id != '') {
                            lurl += '&filterdatafield199=districtid&filtervalue199=' + district_id;
                        }
                        MYAPP.requestLookupWindow(lurl);
                    });

                    $('#btn_view_in_frontend').click(function () {
                        MYAPP.openInNewTab(MYAPP.viewModel._permalink());
                    });
                });
            })(jQuery);
        </script>
    <?php
    }

}