<?php

class QdImgGrp extends QdPostCat
{
    public function __construct(array $attributes = array(), $guard_attributes = true, $instantiating_via_find = false, $new_record = true)
    {
        parent::__construct($attributes, $guard_attributes, $instantiating_via_find, $new_record);
        $this->SETFILTERDEFAULT(array(
            'type' => array('value' => static::$TYPE_IMGGRP, 'exact' => true)
        ));
    }

    public static function getInitObj()
    {
        $obj = new QdImgGrp();//init_obj trên page card sẽ không áp đúng __sys_note_url nếu chọn parent::
        $obj->type = static::$TYPE_IMGGRP;
        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        $obj['__sys_lines_url']['TableRelation'] = array();
        return $obj;
    }
    public function getImgs()
    {
        $record = new QdImage();
        $record->SETFILTERDEFAULT(array(
            'model' => array('value' => $this->getCalledClassName(), 'exact' => true),
            'model_id' => array('value' => $this->id, 'exact' => true),
        ));
        return $record;
    }
}