<?php

class QdImgGrp extends QdPostCat
{
    public function __construct(array $attributes = array(), $guard_attributes = true, $instantiating_via_find = false, $new_record = true)
    {
        parent::__construct($attributes, $guard_attributes, $instantiating_via_find, $new_record);
        $this->SETFILTERDEFAULT(array(
            array('field' => 'type', 'value' => static::$TYPE_IMGGRP, 'operator' => static::$OP_EQUAL)
        ));
    }

    public static function getInitObj()
    {
        $obj = new QdImgGrp();//init_obj trên page card sẽ không áp đúng __sys_note_url nếu chọn parent::
        $obj->type = static::$TYPE_IMGGRP;
        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        $obj['__sys_lines_url']['TableRelation'] = array();
        $obj['type']['Options'] = array(
            static::$TYPE_IMGGRP => array(
                'Caption' => array('en-US' => 'Img group', 'vi-VN' => 'Img Group'),
            ),
        );
        return $obj;
    }
    public function getImgs()
    {
        $record = new QdImage();
        $record->SETFILTERDEFAULT(array(
            array('field' => 'model', 'value' => $this->getCalledClassName(), 'exact' => true, 'operator' => '='),
            array('field' => 'model_id','value' => $this->id, 'exact' => true, 'operator' => '='),
        ));
        return $record;
    }
}