<?php

class QdManufactorGD extends QdManufactor
{
	public function __construct(array $attributes = array(), $guard_attributes = true, $instantiating_via_find = false, $new_record = true)
	{
		parent::__construct($attributes, $guard_attributes, $instantiating_via_find, $new_record);

		$this->SETFILTERDEFAULT(array(
			array('field' => 'type', 'value' => static::$TYPE_MANUFACTOR_GIAYDEP, 'exact' => true, 'operator' => '=')
		));

	}
	public static function getInitObj()
    {
        $tmp = parent::getInitObj();

        $obj = new QdManufactorGD();
        $obj->type = static::$TYPE_MANUFACTOR_GIAYDEP;
        $obj->active = $tmp->active;
        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        //change parent_id filter
        $obj['parent_id']['TableRelation'] = array(
            'Table' => 'QdManufactorGD',
            'Field' => 'id',
            'TableFilter' => array(
                /*array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'type',
                    'Type' => 'FIELD',
                    'Value' => static::$TYPE_MANUFACTOR_GIAYDEP
                )*/
            )
        );
        $obj['type']['Options'] = array(
            static::$TYPE_MANUFACTOR_GIAYDEP => array(
                'Caption' => array('en' => 'Manufactor GD', 'vn' => 'Hãng SX GD'),
            )
        );
        return $obj;
    }
}