<?php

class QdManufactor extends QdProductCat
{
	public function __construct(array $attributes = array(), $guard_attributes = true, $instantiating_via_find = false, $new_record = true)
	{
		parent::__construct($attributes, $guard_attributes, $instantiating_via_find, $new_record);
		$this->SETFILTERDEFAULT(array(
			array('field' => 'type', 'value' => static::$TYPE_MANUFACTOR, 'exact' => true, 'operator' => '=')
		));
	}
	public static function getInitObj()
    {
        $obj = new QdManufactor();
        $obj->type = static::$TYPE_MANUFACTOR;
        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        //change parent_id filter
        $obj['parent_id']['TableRelation'] = array(
            'Table' => 'QdProductCat',
            'Field' => 'id',
            'TableFilter' => array(
                array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'type',
                    'Type' => 'FIELD',
                    'Value' => static::$TYPE_MANUFACTOR
                )
            )
        );
        $obj['__sys_lines_url']['TableRelation'] = array(
            'Table' => 'QdProduct',
            'Field' => 'id',
            'TableFilter' => array(
                array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'manufacturer_id',
                    'Type' => 'FIELD',
                    'Value' => 'id'
                )
            )
        );

        return $obj;
    }
}