<?php

class QdManufactor extends QdProductCat
{
    public static $TYPE2_MANUFACTOR_DEFAULT = 2151;
    public static $TYPE2_MANUFACTOR_QUANAO = 2152;
    public static $TYPE2_MANUFACTOR_GIAYDEP = 2153;
    public static $TYPE2_MANUFACTOR_OTHER = 2154;

	public function __construct(array $attributes = array(), $guard_attributes = true, $instantiating_via_find = false, $new_record = true)
	{
		parent::__construct($attributes, $guard_attributes, $instantiating_via_find, $new_record);
        $this->SETFILTERDEFAULT(array(
			array('field' => 'type', 'value' => static::$TYPE_MANUFACTOR, 'operator' => static::$OP_EQUAL)
		));
	}
	public static function getInitObj()
    {
        $obj = new QdManufactor();
        $obj->type = static::$TYPE_MANUFACTOR;
        $obj->active = true;
        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        //change parent_id filter
        $obj['parent_id']['TableRelation'] = array(
            'Table' => 'QdManufactor',
            'Field' => 'id',
            'TableFilter' => array(
                array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'type',
                    'Type' => 'FIELD',
                    'Value' => static::$TYPE_MANUFACTOR
                )
            )
        );
        $obj['type']['Options'] = array(
            static::$TYPE_MANUFACTOR => array(
                'Caption' => array('en-US' => 'Manufactor', 'vi-VN' => 'Hãng SX'),
            )
        );
        $obj['__sys_lines_url']['TableRelation'] = array(
            'Table' => 'QdProduct',
            'Field' => 'id',
            'TableFilter' => array(
                array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'manufacturer_id',
                    'Type' => 'FIELD',
                    'Value' => 'id'
                )
            )
        );

        return $obj;
    }
    public function getPermalink()
    {
        $query = get_permalink(Qdmvc_Helper::getPageIdByTemplate('page-templates/product-search.php'));
        $query = add_query_arg(array('manufactor-id' => $this->id), $query);
        return $query;
        /*
        $query =  get_site_url();
        $query .= sprintf('/loaisp/%s/%s', $this->id, Qdmvc_Helper::sanitize_title_with_dashes($this->name));
        return $query;*/
    }
}