<?php

class QdProductOrder extends QdRoot
{
    static $table_name = 'mpd_product_order';

    static $belongs_to = array(
        array('product_obj', 'class_name' => 'QdProduct', 'foreign_key' => 'product_id', 'primary_key' => 'id')
    );

    public static $TYPE_SEX_MALE = 1;
    public static $TYPE_SEX_FEMALE = 0;

    public static function getFieldsConfig()
    {
        return array_merge(parent::getFieldsConfig(), array(
            'product_id' => array(
                'Name' => 'product_id',
                'Caption' => array('en-US' => 'Product ID', 'vi-VN' => 'Mã SP'),
                'DataType' => 'Code',
                'Numeric' => true,
                'Description' => '',
                'Editable' => true,
                'InitValue' => '0',
                'FieldClass' => 'Normal',//'FlowField'
                'TableRelation' => array(
                    'Table' => 'QdProduct',
                    'Field' => 'id',
                    'TableFilter' => array(
                    )
                )
            ),
            //SAMPLE FIELD CONFIG
            '_product_name' => array(
                'Name' => '_product_name',
                'Caption' => array('en-US' => 'Product Name', 'vi-VN' => 'Tên SP'),
                'DataType' => 'Text',
                'FieldClass' => 'FlowField',
                'FieldClass_FlowField' => array(
                    'Method' => 'Lookup',
                    'Table' => 'QdProduct',
                    'Field' => 'name',
                    'TableFilter' =>  array(
                        0 => array(
                            'Field' => 'id',
                            'Type' => 'FIELD',
                            'Value' => 'product_id'
                        )
                    )
                )
            ),
            'sex' => array(
                'Caption' => array('en-US' => 'Sex', 'vi-VN' => 'Giới tính'),
                'DataType' => 'Option',
                'Options' => array(
                    static::$TYPE_SEX_MALE => array(
                        'Caption' => array('en-US' => 'Male', 'vi-VN' => 'Nam'),
                    ),
                    static::$TYPE_SEX_FEMALE => array(
                        'Caption' => array('en-US' => 'Female', 'vi-VN' => 'Nữ'),
                    ),
                )
            ),
            'customer_name' => array(
                'Caption' => array('en-US' => 'Customer Name', 'vi-VN' => 'Tên KH')
            ),
            'customer_email' => array(
                'Caption' => array('vi-VN' => 'Email KH'),
            ),
            'customer_address' => array(
                'Caption' => array('vi-VN' => 'Địa chỉ KH'),
            ),
            'customer_phone' => array(
                'Caption' => array('vi-VN' => 'SĐT KH'),
            ),
            'count' => array(
                'Caption' => array('en-US' => 'Quantity', 'vi-VN' => 'SL đặt')
            ),
            'done' => array(
                'DataType' => 'Boolean',
                'Caption' => array('vi-VN' => 'Hoàn tất'),
            ),
            'mota' => array(
                'Caption' => array('vi-VN' => 'Mô tả'),
            ),
        )); // TODO: Change the autogenerated stub
    }

    public function getProduct()
    {
        return QdProduct::GET($this->product_id);
        //return $this->product_obj;
    }

    public function save($validate = true, $location='')
    {
        if(!$this->is_new_record())
        {
            if($this->done) {
                if ($this->xRec()->done) {
                    $this->pushValidateError('', 'Không thể sửa khi Done = true');
                    return false;
                }
            }
        }
        return parent::save($validate, $location);
    }
    protected function countOnValidate($field_name)
    {
        if($this->count<=0)
        {
            $this->pushValidateError($field_name, 'Quantity phải lớn hơn 0', 'error', 'count');
        }
    }
    protected function customer_emailOnValidate($field_name)
    {
        if($this->$field_name!='')
        {
            if (!filter_var($this->$field_name, FILTER_VALIDATE_EMAIL)) {
                $this->pushValidateError($field_name, 'Email không đúng định dạng', 'warning', $field_name);
            }
        }
    }

    protected function product_idOnValidate($field_name)
    {
        //check exit
        if($this->$field_name>0)
        {
            if(QdProduct::GET($this->$field_name)==null)
            {
                $this->pushValidateError($field_name, 'Product không tồn tại!');
                if(!$this->is_new_record())
                {
                    $this->$field_name = $this->xRec()->$field_name;
                }
            }
        }
    }

    protected function motaOnValidate($field_name)
    {
        if($this->$field_name=='')
        {
            $this->$field_name = $this->customer_name;
            $this->pushValidateError($field_name, 'Mota tự động bằng Customer Name', 'info');
        }
    }
    public function delete($location='')
    {
        if($this->done)
        {
            $this->pushValidateError('', 'Không thể xóa khi Done = true');
            return false;
        }
        return parent::delete($location);
    }
    public function fn_send_email()
    {
        if(!is_email($this->customer_email))
        {
            return false;
        }
        $pro = $this->getProduct();
        $pro_name = '';
        $pro_code = '';
        if(!Qdmvc_Helper::isNullOrEmpty($pro))
        {
            $pro_name = $pro->name;
            $pro_code = $pro->code;
        }
        else
        {
            return false;
        }

        $p_order_setup = QdSetupProductOrder::GET();
        if(Qdmvc_Helper::isNullOrEmpty($p_order_setup))
        {
            return false;
        }

        $tpl = $p_order_setup->order_done_email_tpl;

        $sex_title = $this->sex==1?'Anh':'Chị';


        $tpl = str_replace(array('{sex}', '{customer_name}', '{product_name}', '{product_code}'), array($sex_title, $this->customer_name, $pro_name, $pro_code), $tpl);
        $title = $p_order_setup->order_done_email_title;
        $content = $tpl;
        return Qdmvc_Helper::sendEmail($this->customer_email, $title, $content);
    }
}