<?php

class QdPromotionCat extends QdProductCat
{
    public static $TYPE_PROMOTION = 137;

    public static function getInitObj()
    {
        $tmp = parent::getInitObj();

        $obj = new QdPromotionCat();
        $obj->transferFieldsFrom($tmp);
        $obj->type = static::$TYPE_PROMOTION;

        return $obj;
    }

    public static function getFieldsConfig()
    {
        $obj = parent::getFieldsConfig(); // TODO: Change the autogenerated stub
        //change parent_id filter
        $obj['parent_id']['TableRelation'] = array(
            'Table' => 'QdPromotionCat',
            'Field' => 'id',
            'TableFilter' => array(
                /*array(
                    'Condition' => array(
                        'Field' => '',
                        'Type' => 'CONST',//'FIELD'
                        'Value' => ''
                    ),
                    'Field' => 'type',
                    'Type' => 'FIELD',
                    'Value' => static::$TYPE_PROMOTION
                )*/
            )
        );
        $obj['type']['Options'] = array(
            static::$TYPE_PROMOTION => array(
                'Caption' => array('en-US' => 'Promotion', 'vi-VN' => 'Khuyến mãi'),
            ),
        );
        return $obj;
    }
}